-- ================================================================
-- BASE DE DATOS - MÓDULO DE NOTIFICACIONES
-- Supabase / PostgreSQL
-- Compatible con el modelo y repositorio actuales del backend.
-- ================================================================

-- ----------------------------------------------------------------
-- AUTH
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.auth_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    email TEXT NOT NULL,
    url_recuperacion TEXT,
    procesado BOOLEAN NOT NULL DEFAULT FALSE,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    procesado_at TIMESTAMPTZ
);

-- ----------------------------------------------------------------
-- ENTRADAS
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.entradas_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id TEXT NOT NULL,
    evento_id TEXT NOT NULL,
    nombre_evento TEXT NOT NULL,
    fecha_evento TIMESTAMPTZ NOT NULL,
    cantidad_entradas INTEGER NOT NULL CHECK (cantidad_entradas > 0),
    email TEXT,
    codigo_qr TEXT,
    entrada_activa BOOLEAN NOT NULL DEFAULT TRUE,
    estado_evento TEXT NOT NULL DEFAULT 'PROGRAMADO',
    fecha_emision TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (usuario_id, evento_id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'check_entradas_usuario_estado_evento'
    ) THEN
        ALTER TABLE public.entradas_usuario
        ADD CONSTRAINT check_entradas_usuario_estado_evento
        CHECK (estado_evento IN (
            'PROGRAMADO', 'CANCELADO', 'FINALIZADO', 'REPROGRAMADO', 'BORRADOR'
        ));
    END IF;
END $$;

-- ----------------------------------------------------------------
-- RECORDATORIOS
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recordatorios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada_usuario_id BIGINT NOT NULL
        REFERENCES public.entradas_usuario(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL,
    fecha_programada TIMESTAMPTZ NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE',
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_error TEXT,
    enviado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (entrada_usuario_id, tipo)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'check_recordatorios_tipo'
    ) THEN
        ALTER TABLE public.recordatorios
        ADD CONSTRAINT check_recordatorios_tipo
        CHECK (tipo IN ('RECORDATORIO_24H', 'RECORDATORIO_30M', 'INICIO_EVENTO'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'check_recordatorios_estado'
    ) THEN
        ALTER TABLE public.recordatorios
        ADD CONSTRAINT check_recordatorios_estado
        CHECK (estado IN ('PENDIENTE', 'PROCESANDO', 'ENVIADO', 'ERROR', 'CANCELADO'));
    END IF;
END $$;

-- ----------------------------------------------------------------
-- NOTIFICACIONES
--
-- IMPORTANTE: esta estructura coincide con src/models/Notificacion.js
-- y src/repositories/notificacionRepository.js.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notificaciones (
    id_notificacion TEXT PRIMARY KEY,
    usuario_id TEXT NOT NULL,
    tipo TEXT NOT NULL,
    titulo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    datos JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado TEXT NOT NULL DEFAULT 'NO_LEIDA',
    fecha_lectura TIMESTAMPTZ,
    fecha_eliminacion TIMESTAMPTZ,
    intentos_envio INTEGER NOT NULL DEFAULT 0,
    error_envio TEXT
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'check_notificaciones_tipo'
    ) THEN
        ALTER TABLE public.notificaciones
        ADD CONSTRAINT check_notificaciones_tipo
        CHECK (tipo IN (
            'COMPRA',
            'RECORDATORIO',
            'RECORDATORIO_24H',
            'RECORDATORIO_30M',
            'INICIO_EVENTO',
            'EVENTO_CAMBIO',
            'CAMBIO_EVENTO',
            'CANCELACION_EVENTO',
            'RECUPERACION_PASSWORD',
            'CREACION_STAFF'
        ));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'check_notificaciones_estado'
    ) THEN
        ALTER TABLE public.notificaciones
        ADD CONSTRAINT check_notificaciones_estado
        CHECK (estado IN ('NO_LEIDA', 'LEIDA', 'ELIMINADA'));
    END IF;
END $$;

-- ----------------------------------------------------------------
-- AUDITORIA Y REINTENTOS DE ENVIO
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.envios_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacion_id TEXT NOT NULL
        REFERENCES public.notificaciones(id_notificacion) ON DELETE CASCADE,
    canal TEXT NOT NULL,
    estado TEXT NOT NULL,
    intento INTEGER NOT NULL DEFAULT 1,
    error TEXT,
    enviado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'envios_notificacion_canal_check'
    ) THEN
        ALTER TABLE public.envios_notificacion
        ADD CONSTRAINT envios_notificacion_canal_check
        CHECK (canal IN ('APP', 'EMAIL'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'envios_notificacion_estado_check'
    ) THEN
        ALTER TABLE public.envios_notificacion
        ADD CONSTRAINT envios_notificacion_estado_check
        CHECK (estado IN ('PENDIENTE', 'ENVIADO', 'ERROR'));
    END IF;
END $$;

-- ----------------------------------------------------------------
-- INDICES
-- ----------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_entradas_usuario_evento
ON public.entradas_usuario(evento_id);

CREATE INDEX IF NOT EXISTS idx_entradas_usuario_usuario
ON public.entradas_usuario(usuario_id);

CREATE INDEX IF NOT EXISTS idx_entradas_usuario_activas
ON public.entradas_usuario(evento_id)
WHERE entrada_activa = TRUE;

CREATE INDEX IF NOT EXISTS idx_recordatorios_pendientes
ON public.recordatorios(fecha_programada)
WHERE estado = 'PENDIENTE';

CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario
ON public.notificaciones(usuario_id);

CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_fecha
ON public.notificaciones(usuario_id, fecha_emision DESC);

CREATE INDEX IF NOT EXISTS idx_notificaciones_no_leidas
ON public.notificaciones(usuario_id)
WHERE estado = 'NO_LEIDA';

-- ----------------------------------------------------------------
-- TRIGGER DE RECORDATORIOS
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.crear_recordatorios()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.recordatorios (entrada_usuario_id, tipo, fecha_programada)
    VALUES
        (NEW.id, 'RECORDATORIO_24H', NEW.fecha_evento - INTERVAL '24 hours'),
        (NEW.id, 'RECORDATORIO_30M', NEW.fecha_evento - INTERVAL '30 minutes'),
        (NEW.id, 'INICIO_EVENTO', NEW.fecha_evento)
    ON CONFLICT (entrada_usuario_id, tipo) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_crear_recordatorios ON public.entradas_usuario;

CREATE TRIGGER trigger_crear_recordatorios
AFTER INSERT ON public.entradas_usuario
FOR EACH ROW
EXECUTE FUNCTION public.crear_recordatorios();

-- ----------------------------------------------------------------
-- SUPABASE REALTIME
-- ----------------------------------------------------------------
-- En Supabase: Database -> Replication -> habilitar public.notificaciones.
-- Si prefieres SQL, ejecuta una sola vez:
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.notificaciones;
